server:
  port: 8080
  servlet:
    context-path: /api/
spring:
  mvc:
    servlet:
      load-on-startup: 1
  datasource:
    driverClassName: org.h2.Driver
    username: root
    password: 123456
    platform: h2
    url: jdbc:h2:mem:galaxia
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    show-sql: true
  cache:
    # Redis
    type: REDIS
  redis:
    host: 127.0.0.1
    port: 6379
    # password: YOU ARE SUGGESTED TO SET PASSWORD IF NEEDED.
    timeout: 10000
    # Redis默认情况下有16个分片，这里配置具体使用的分片，默认是0
    database: 0
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 10
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0
